#!/bin/python3

import math
import os
import random
import re
import sys
from collections import defaultdict
#
# Complete the 'arrayManipulation' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def arrayManipulation(n, queries):
    # Write your code here
    dicty = defaultdict(int)
    for start,end, k in queries:
        dicty[start] += k
        dicty[end+1] -= k
    pairs = []
    for key,val in dicty.items():
        pairs.append((key,val))
    pairs.sort()
    _max = float("-inf")
    cur_sum = 0
    for pair in pairs:
        cur_sum += pair[1]
        _max = max(cur_sum,_max)
    return _max
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
